language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv -in application.properties.enc -out application.properties -d
  - openssl aes-256-cbc -K $encrypted_b846c1a3db1c_key -iv $encrypted_b846c1a3db1c_iv -in application-oauth.properties.enc -out application-oauth.properties -d
  - mv application.properties ./src/main/resources
  - mv application-oauth.properties ./src/main/resources

script: "./gradlew clean build"

before_deploy:
  - zip -r slack *
  - mkdir -p deploy
  - mv slack.zip deploy/slack.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: slackclonetravis
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

notifications:
  email:
    recipients:
      - dev.sunnylee@gmail.com
      - efubslack@gmail.com
